### ISSUE TITLE
sorry to bother you

### ISSUE THREAD

**Issue by sukanemoero** [sdp8483/MSP430F5529_SSD1306_OLED#1]
Is there a version for msp430fr2355?
actually, I dont really understand how ssd1306 works in fr2355

**Comment by sdp8483** [comment]
At a quick glance it seems like you should be able port this code for the MSP430F5529 to the MSP430FR2355. They both use the same eUSCI module for the I2C peripheral. 

Give it a try by copying the `main.c`, `ssd1306.h`, `ssd1306.c`, `fondt_5x7.h`, `i2c.h`, `i2c.c`, `clock.c`, and `clock.h` into a CCS project for the MSP430FR2355. Hit compile and hope for the best. 

The complier's error output should give you a hint of what went wrong. It's possible that you may need to modify the clock setup code and maybe the ISR for the I2C peripheral. 

I'm not exactly sure and I don't believe I have a MSP430FR2355 to give it a try. It's been a few years since I have developed firmware for a MSP430 part.

**Comment by sukanemoero** [comment]
```
"../clock.c", line 18: error #20: identifier "UCSCTL3" is undefined
"../clock.c", line 19: error #20: identifier "UCSCTL4" is undefined
"../clock.c", line 22: error #20: identifier "UCSCTL0" is undefined
"../clock.c", line 23: error #20: identifier "UCSCTL1" is undefined
"../clock.c", line 24: error #20: identifier "UCSCTL2" is undefined
"../clock.c", line 39: error #20: identifier "UCSCTL7" is undefined
"../clock.c", line 39: error #20: identifier "XT2OFFG" is undefined
"../clock.c", line 39: error #20: identifier "XT1LFOFFG" is undefined
"../clock.c", line 34: remark #1527-D: (ULP 2.1) Detected SW delay loop using __delay_cycles. Recommend using a timer module instead
"../clock.c", line 50: error #20: identifier "SVSMHCTL" is undefined
"../clock.c", line 50: error #20: identifier "SVSHRVL0" is undefined
"../clock.c", line 50: error #20: identifier "SVMHE" is undefined
"../clock.c", line 50: error #20: identifier "SVSMHRRL0" is undefined
"../clock.c", line 52: error #20: identifier "SVSMLCTL" is undefined
"../clock.c", line 52: error #20: identifier "SVSLE" is undefined
"../clock.c", line 52: error #20: identifier "SVMLE" is undefined
"../clock.c", line 52: error #20: identifier "SVSMLRRL0" is undefined
"../clock.c", line 54: error #20: identifier "SVSMLDLYIFG" is undefined
"../clock.c", line 56: error #20: identifier "SVMLVLRIFG" is undefined
"../clock.c", line 56: error #20: identifier "SVMLIFG" is undefined
"../clock.c", line 58: error #20: identifier "PMMCOREV0" is undefined
"../clock.c", line 63: error #20: identifier "SVSLRVL0" is undefined
```
some error at clock.c, but i dont know what are those

**Comment by sdp8483** [comment]
ok, clock setup is different. Remove `clock.h` and `clock.c` and also remove `clock_init()` in `main.c`.

You can try to run without setting the clock speed, it will run at whatever the default is. I don't know what that is, you would have to read through the datasheet and see what the registers are set to at reset.

If you want 24MHz then I found an example from TI in the Resource Explorer, `msp430fr235x_CS_09.c`. This may work by placing the code below after `WDTCTL = WDTPW + WDTHOLD;`.

    // Configure two FRAM waitstate as required by the device datasheet for MCLK
    // operation at 24MHz(beyond 8MHz) _before_ configuring the clock system.
    FRCTL0 = FRCTLPW | NWAITS_2;

    __bis_SR_register(SCG0);                           // disable FLL
    CSCTL3 |= SELREF__REFOCLK;                         // Set REFO as FLL reference source
    CSCTL0 = 0;                                        // clear DCO and MOD registers
    CSCTL1 |= DCORSEL_7;                               // Set DCO = 24MHz
    CSCTL2 = FLLD_0 + 731;                             // DCOCLKDIV = 24MHz
    __delay_cycles(3);  
    __bic_SR_register(SCG0);                           // enable FLL
    while(CSCTL7 & (FLLUNLOCK0 | FLLUNLOCK1));         // FLL locked
    
    CSCTL4 = SELMS__DCOCLKDIV | SELA__REFOCLK;        // set default REFO(~32768Hz) as ACLK source, ACLK = 32768Hz
                                                       // default DCOCLKDIV as MCLK and SMCLK source

**Comment by sukanemoero** [comment]
it stuck in LPM when i run i2c_write at first
in this place:
```
void i2c_write(unsigned char *DataBuffer, unsigned char ByteCtr) {     
          
     // ...
    
    __bis_SR_register(LPM0_bits + GIE);      //<========================
    __no_operation();                     
     while (UCB1CTL1 & UCTXSTP); 
} 
```
before this, its running ```ssd1306_command(SSD1306_DISPLAYOFF);``` in ```ssd1306_init()```     

```__even_in_range(UCB1IV,12)``` result 4 so it dont exit the LPM i thought

and, FR2355 doesnt have P4SEL actually
i edited ```P4SEL |= SDA | SCL;``` to  ```P4SEL0 |= SDA | SCL;``` 
and i edited SDA and SCL pin
```
#define SDA BIT6
#define SCL BIT7
```
P4.6 connects to OLED's SDA pin
P4.7 connects to OLED's SCL pin
in fect, I don't know if this is correct

**Comment by sdp8483** [comment]
Your best bet is to find in [TI Resource Explorer](https://dev.ti.com/tirex/explore) example [i2c code ](https://dev.ti.com/tirex/explore/node?node=A__AApgSAN1LLQuiHdYj7BRKw__msp430ware__IOGqZri__LATEST) and make sure you can get that to work. Then build from there.

**Comment by sukanemoero** [comment]
i see
i can try it
